# This file is part of the RISC OS Toolkit (RTK).
# Copyright © 2003-2005 Graham Shaw.
# Distribution and use are subject to the GNU Lesser General Public License,
# a copy of which may be found in the file !RTK.Copyright.

CPPFLAGS = -Irtk_build:
CXXFLAGS = -mthrowback -munixlib -mpoke-function-name \
 -Wall -W -Wno-unused -Wno-uninitialized -O2

include fixdeps:Rules/make

CCSRC = $(wildcard *.cc)

all: timestamp

timestamp: $(CCSRC:.cc=.o)
	touch timestamp

include $(CCSRC:.cc=.d)
